name: atividade_03
description: Aplicação Dart com acesso ao SQLite e tratamento de exceções.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3